# Generated by Django 6.1.2 on 2026-10-10 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(choices=[('overdue_unfulfilled', 'Overdue unfulfilled'), ('stockout', 'Stockout'), ('delivery_exception', 'Delivery exception'), ('missing_tracking', 'Missing tracking'), ('stale_tracking', 'Stale tracking'), ('late_delivery', 'Late delivery'), ('suspicious_address', 'Suspicious address')], max_length=30)),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('snoozed', 'Snoozed'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('auto', 'Auto (problem cleared)'), ('manual', 'Manual (closed by a person)')], max_length=10)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Facts found by the rule.')),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, help_text='Set for shipment-level rules, empty for order-level rules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='orders.shipment')),
            ],
            options={
                'verbose_name': 'exception',
                'ordering': ['severity', 'first_detected_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_system', models.BooleanField(default=False, help_text='Status change, not a typed comment.')),
                ('author', models.ForeignKey(blank=True, help_text='Empty for changes made by the rules engine.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_notes', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='issues.issue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(choices=[('overdue_unfulfilled', 'Overdue unfulfilled'), ('stockout', 'Stockout'), ('delivery_exception', 'Delivery exception'), ('missing_tracking', 'Missing tracking'), ('stale_tracking', 'Stale tracking'), ('late_delivery', 'Late delivery'), ('suspicious_address', 'Suspicious address')], max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('threshold', models.PositiveIntegerField(blank=True, help_text='For example 2 (business days).', null=True)),
                ('threshold_unit', models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days'), ('business_days', 'Business days')], max_length=20)),
                ('cutoff_time', models.TimeField(blank=True, help_text='Overdue rule only: orders paid after this local time count from the next business day.', null=True)),
            ],
            options={
                'ordering': ['severity', 'rule_code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rule_code__in', ['overdue_unfulfilled', 'stockout', 'delivery_exception', 'missing_tracking', 'stale_tracking', 'late_delivery', 'suspicious_address'])), name='rule_setting_rule_code_valid'), models.CheckConstraint(condition=models.Q(('severity__in', [1, 2, 3])), name='rule_setting_severity_valid'), models.CheckConstraint(condition=models.Q(('threshold_unit', ''), ('threshold_unit__in', ['hours', 'days', 'business_days']), _connector='OR'), name='rule_setting_unit_valid'), models.CheckConstraint(condition=models.Q(models.Q(('threshold__isnull', True), ('threshold_unit', '')), models.Q(('threshold__isnull', False), models.Q(('threshold_unit', ''), _negated=True)), _connector='OR'), name='rule_setting_threshold_has_unit')],
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', 'severity'], name='issue_status_severity_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'acknowledged', 'snoozed'])), fields=('order', 'shipment', 'rule_code'), name='issue_one_active_per_target', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('rule_code__in', ['overdue_unfulfilled', 'stockout', 'delivery_exception', 'missing_tracking', 'stale_tracking', 'late_delivery', 'suspicious_address'])), name='issue_rule_code_valid'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'acknowledged', 'snoozed', 'resolved'])), name='issue_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', [1, 2, 3])), name='issue_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('resolution', ''), ('resolution__in', ['auto', 'manual']), _connector='OR'), name='issue_resolution_valid'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_code__in', ['delivery_exception', 'stale_tracking', 'late_delivery']), ('shipment__isnull', False)), models.Q(models.Q(('rule_code__in', ['delivery_exception', 'stale_tracking', 'late_delivery']), _negated=True), ('shipment__isnull', True)), _connector='OR'), name='issue_shipment_matches_rule'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'snoozed'), _negated=True), ('snoozed_until__isnull', False), _connector='OR'), name='issue_snoozed_has_until'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'resolved'), _negated=True), models.Q(('resolved_at__isnull', False), models.Q(('resolution', ''), _negated=True)), _connector='OR'), name='issue_resolved_has_resolution'),
        ),
    ]
