# Generated by Django 6.1.2 on 2026-10-10 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('orders', 'Orders'), ('inventory', 'Inventory'), ('tracking', 'Tracking')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Empty when the import ran from the command line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['orders', 'inventory', 'tracking'])), name='import_log_kind_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['running', 'succeeded', 'failed'])), name='import_log_status_valid')],
            },
        ),
    ]
