# Generated by Django 6.1.2 on 2026-10-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['sku'], 'verbose_name': 'SKU', 'verbose_name_plural': 'SKUs'},
        ),
        migrations.AlterModelOptions(
            name='inventorylevel',
            options={'verbose_name': 'stock level'},
        ),
    ]
