"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from .env into os.environ (local development).
# Variables already set in the real environment (Docker, hosting) win.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Required: the app refuses to start without it.
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so a missing variable never turns debug on.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    # Admin theme. Must come before django.contrib.admin so its templates win.
    'unfold',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ShipRadar apps
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Same POSTGRES_* variables that docker-compose.yml uses to create the database.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['POSTGRES_DB'],
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Custom user model. Must be set before the first `migrate`.
AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Display and form input use the warehouse's time zone.
# With USE_TZ = True, datetimes are still stored in UTC.
TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Login
# https://docs.djangoproject.com/en/6.1/ref/settings/#login-redirect-url

# Where to go after logging in when no ?next= is given.
# Unfold's login form does not send `next`, so without this a direct visit to
# /admin/login/ ends on Django's default /accounts/profile/ (404).
LOGIN_REDIRECT_URL = 'admin:index'


# Django admin theme (django-unfold)
# https://unfoldadmin.com/docs/configuration/settings/

UNFOLD = {
    'SITE_TITLE': 'ShipRadar Admin',
    'SITE_HEADER': 'ShipRadar',
    'SITE_SUBHEADER': 'Back office',
    'SITE_SYMBOL': 'radar',  # Material Symbols icon name
    'COLORS': {
        # Navy primary, hue 257. 950 is the portfolio navy (#0F1E33).
        # 600 = buttons/links in light mode, 500 = text/buttons in dark mode.
        'primary': {
            '50': 'oklch(97.5% 0.011 257)',
            '100': 'oklch(94.5% 0.022 257)',
            '200': 'oklch(88.5% 0.045 257)',
            '300': 'oklch(80% 0.075 257)',
            '400': 'oklch(70% 0.105 257)',
            '500': 'oklch(60.5% 0.125 257)',
            '600': 'oklch(43% 0.115 257)',
            '700': 'oklch(37% 0.098 257)',
            '800': 'oklch(31.5% 0.08 257)',
            '900': 'oklch(27% 0.062 257)',
            '950': 'oklch(23.4% 0.046 257)',
        },
    },
}
