# Generated by Django 6.1.2 on 2026-10-10 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('financial_status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('voided', 'Voided')], max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('partial', 'Partially fulfilled'), ('fulfilled', 'Fulfilled')], default='unfulfilled', max_length=20)),
                ('placed_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Cancelled orders are ignored by every rule.', null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_method', models.CharField(blank=True, max_length=100)),
                ('ship_name', models.CharField(blank=True, max_length=255)),
                ('ship_address1', models.CharField(blank=True, max_length=255)),
                ('ship_address2', models.CharField(blank=True, max_length=255)),
                ('ship_city', models.CharField(blank=True, max_length=100)),
                ('ship_province', models.CharField(blank=True, max_length=50)),
                ('ship_zip', models.CharField(blank=True, max_length=20)),
                ('ship_country', models.CharField(blank=True, help_text='ISO code, e.g. US.', max_length=2)),
                ('fulfillment_location', models.ForeignKey(help_text='Warehouse that ships this order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.location')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(choices=[('ups', 'UPS'), ('usps', 'USPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('other', 'Other')], max_length=10)),
                ('tracking_number', models.CharField(max_length=64)),
                ('shipped_at', models.DateTimeField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('label_created', 'Label created'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('exception', 'Exception'), ('returned_to_sender', 'Returned to sender')], default='label_created', max_length=20)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
            ],
            options={
                'ordering': ['-shipped_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('label_created', 'Label created'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('exception', 'Exception'), ('returned_to_sender', 'Returned to sender')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.shipment')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fulfillment_status', 'financial_status'], name='order_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('financial_status__in', ['pending', 'authorized', 'partially_paid', 'paid', 'partially_refunded', 'refunded', 'voided'])), name='order_financial_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('fulfillment_status__in', ['unfulfilled', 'partial', 'fulfilled'])), name='order_fulfillment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='order_total_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_unit_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'last_event_at'], name='shipment_status_last_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('carrier', 'tracking_number'), name='shipment_unique_carrier_tracking'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('carrier__in', ['ups', 'usps', 'fedex', 'dhl', 'other'])), name='shipment_carrier_valid'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['label_created', 'in_transit', 'out_for_delivery', 'delivered', 'exception', 'returned_to_sender'])), name='shipment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='trackingevent',
            constraint=models.UniqueConstraint(fields=('shipment', 'occurred_at', 'status'), name='tracking_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='trackingevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['label_created', 'in_transit', 'out_for_delivery', 'delivered', 'exception', 'returned_to_sender'])), name='tracking_event_status_valid'),
        ),
    ]
